name: CI

on:
  push:
    branches:
      - master

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'test things' > .test
      - uses: actions/upload-artifact@master
        with:
          name: test
          path: .test

  check-dep:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/download-artifact@master
        with:
          name: test
          path: .test
      - run: ls -lA

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/docker/cli@master
      - env:
          GCR_SERVICE_ACCOUNT_JSON: ${{ secrets.GCR_SERVICE_ACCOUNT_JSON }}
        run: echo $GCR_SERVICE_ACCOUNT_JSON | docker login -u _json_key --password-stdin https://eu.gcr.io
      - env:
          DOCKER_BUILDKIT: 1
        run: docker build -t eu.gcr.io/kunkels-core/actions:v0.1.0 .
      - run: docker push eu.gcr.io/kunkels-core/actions:v0.1.0
